name: Auto Deploy

on: 
  pull_request:
    branches:
      - 'main'
      - 'development'
      - 'qa'
      - 'staging' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore Dependencies
        run: dotnet restore WebApp.sln
      
      - name: Build API
        run: dotnet build WebApp/WebApp.csproj --no-restore

  deploy-to-production:
    needs: build

    if: github.head_ref == 'production'

    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Deploy
      run: echo "Deployement to production"

  deploy-to-staging:
    needs: build

    if: github.head_ref == 'staging'

    runs-on: ubuntu-latest

    environment: staging

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3
      with:
        ref: 'staging'

    - name: Deploy
      run: echo "Deployement to staging"

  deploy-to-development:
    needs: build

    if: github.head_ref == 'development'

    runs-on: ubuntu-latest

    environment: development

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3
      with:
        ref: 'development'

    - name: Deploy
      run: echo "Deployement to development"

  deploy-to-qa:
    needs: build

    if: github.head_ref == 'qa'

    runs-on: ubuntu-latest

    environment: development

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3
      with:
        ref: 'qa'

    - name: Deploy
      run: echo "Deployement to qa"