name: Build

on: 
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore WebApp.sln

    - name: Build API
      run: dotnet build WebApp/WebApp.csproj --no-restore