name: Deploy

on: 
  workflow_dispatch:
    branches: [main]
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment

jobs:
  deploy to ${{ inputs.environment }}:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    # - name: Setup .NET 7
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x

    # - name: Restore Dependencies
    #   run: dotnet restore WebApp.sln

    # - name: Build API
    #   run: dotnet build WebApp/WebApp.csproj --no-restore

    - name: Deploy
      run: echo "Deployement to ${{ inputs.environment }}"