name: Pull Request detailer

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  dump_github_context:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  get_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commits
        uses: actions/github-script@v6
        with:
          script: |
            const baseSHA = context.payload.pull_request.base.sha;
            const headSHA = context.payload.pull_request.head.sha;
            console.log(`Base branch last commit: ${baseSHA}`);
            console.log(`Head branch last commit: ${headSHA}`);
            
            const perPage = 100;
            let page = 1;
            let allCommits = [];
            
            while (true) {
              const compare = await github.rest.repos.compareCommitsWithBasehead({
                owner: context.repo.owner,
                repo: context.repo.repo,
                basehead: `${baseSHA}...${headSHA}`,
                per_page: perPage,
                page: page
              });
            
              if (compare.data.commits.length === 0) {
                break;
              }
              
              allCommits = allCommits.concat(compare.data.commits);
              page++;
            }
            
            console.log('Commits:', allCommits);
            
            const mergeCommits = allCommits.filter(commit => commit.parents.length > 1 && commit.commit.verification.verified == true);
            
            console.log('Merge Commits:', JSON.stringify(mergeCommits));

            const pullRequests = [];
            for (const commit of mergeCommits) {
              const commitDetails = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commit.sha
              });
              const pullRequest = commitDetails.data.pull_request;
              if (pullRequest) {
                pullRequests.push(pullRequest);
              }
            }
            
            console.log('Associated Pull Requests:', JSON.stringify(pullRequests));