name: Pull Request detailer

on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  dump_github_context:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  get_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commits
        uses: actions/github-script@v6
        with:
          script: |
            const baseSHA = context.payload.pull_request.base.sha;
            const headSHA = context.payload.pull_request.head.sha;
            console.log(`Base branch last commit: ${baseSHA}`);
            console.log(`Head branch last commit: ${headSHA}`);
            
            let page = 1;
            let commits = [];
            let foundBaseSHA = false;
            while (true) {
              const response = await github.repos.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: headSHA,
                per_page: 100,
                page: page
              });
              if (response.data.length === 0) break;
              for (const commit of response.data) {
                commits.push(commit);
                if (commit.sha === baseSHA) {
                  foundBaseSHA = true;
                  break;
                }
              }
              if (foundBaseSHA) break;
              page++;
            }
            
            console.log('Commits:', commits);